---

- hosts: web
  tasks:
    - name: copy resources
      local_action: command rsync -r ../resources cloudsigma@{{ansible_ssh_host}}:/opt/thehat/

    - name: bust caches for game
      script: infrastructure/cache_busting.py /opt/thehat/resources/public/game.html /opt/thehat/resources/public/thehat.css /opt/thehat/resources/public/thehat.js

    - name: bust caches for index
      script: infrastructure/cache_busting.py /opt/thehat/resources/public/index.html /opt/thehat/resources/public/thehat.css /opt/thehat/resources/public/thehat.js

    - name: bust manifest cache
      shell: "# `date`" >> /opt/thehat/resources/public/cache.manifest

    - name: gzip everything
      script: gzip.sh

  handlers:
    - name: restart app
      service: name=thehat state=restarted
