---

- hosts: web
  tasks:
    - name: copy resources
      local_action: command rsync -r ../resources cloudsigma@{{ansible_ssh_host}}:/opt/thehat/

    - name: gzip everything
      script: gzip.sh

  handlers:
    - name: restart app
      service: name=thehat state=restarted
