---

- hosts: web
  tasks:
    - name: copy resources
      local_action: command rsync -r ../resources root@{{ansible_ssh_host}}:/opt/thehat/

    - name: bust caches for en game
      script: cache_busting.py /opt/thehat/resources/public/game_en.html /opt/thehat/resources/public/thehat.css /opt/thehat/resources/public/thehat_en.js

    - name: bust caches for ru game
      script: cache_busting.py /opt/thehat/resources/public/game_ru.html /opt/thehat/resources/public/thehat.css /opt/thehat/resources/public/thehat_ru.js

    - name: bust caches for index
      script: cache_busting.py /opt/thehat/resources/public/index.html /opt/thehat/resources/public/thehat.css

    - name: bust manifest cache
      script: manifest_bust.sh

    - name: gzip everything
      script: gzip.sh
