---

- hosts: web
  sudo: yes
  vars_files:
    - vars.yml

  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: add webupd8team ppa
      shell: add-apt-repository ppa:webupd8team/java -y

    - name: add nginx ppa
      shell: add-apt-repository ppa:nginx/stable -y

    - name: update system
      apt: update_cache=yes upgrade=yes

    - name: accept Oracle license
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: install JDK8
      apt: pkg={{ item }} state=present
      with_items:
        - oracle-java8-installer
        - oracle-java8-set-default

    - name: install nginx
      apt: pkg=nginx state=present

    - name: write nginx.conf
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-enabled/main
      notify:
        - restart nginx

    - name: delete default vhost
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx

    - name: ensure app folder
      file: path=/opt/thehat state=directory

    - name: ensure log folder
      file: path=/opt/thehat/logs state=directory

    - name: copy run.sh
      template: src=templates/run.sh.j2 dest=/opt/thehat/run.sh mode=0777

    - name: copy init script
      template: src=templates/initscript.j2 dest=/etc/init.d/thehat mode=0777

    - name: install pip
      apt: pkg=python-pip state=present

    - name: install python deps
      shell: pip install beautifulsoup4 requests

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
